### ISSUE TITLE
RubyML

### ISSUE THREAD

**Issue by arbox** [himkt/rblearn#1]
Dear @himkt ,

we've recently added `rblearn` to our RubyML list: https://github.com/arbox/machine-learning-with-ruby

In order to connect all Ruby & ML related projects we introduced the `rubyml` topic on GitHub.

Please cosider adding the `rubyml` topic to this repository as well so that the Ruby community can discover `rblearn` faster :smiley: 

Thank you in advance!

**Comment by himkt** [comment]
Thanks for the comment @arbox !
I will implement some ML features when I have enough time 👍 

On the other hand, it is difficult to implement various ML features.
There is the project named [pycall](https://github.com/mrkn/pycall) which uses existing python resources.
I'm sorry if you have already know but I wanna let you know 😄 

Thanks !

**Comment by arbox** [comment]
Hi @himkt ,

you don't have to implement additional features now :smile: You can add the `rubyml` topic to your repository on GitHub: https://github.com/blog/2309-introducing-topics

This will enhance the discoverability of your project and connects it with the RubyML community on GitHub. That was the idea behind my request.

For sure I know about the effort by @mrkn and use his PyCall. And I hope it gets mature very quickly.

**Comment by himkt** [comment]
Oh I see, I'm misunderstood!
I added ```rubyml``` topic, thanks for the recommendation 🌻
